version: '3'

tasks:
  new:article:
    desc: create new article. [command] task new:article
    dir: $HOME/note
    cmds:
      - note-cli create article -a Junichi.Y -t .
    silent: true
  new:image:
    desc: create new article image. [command] task new:image -- [directory name] 
    dir: $HOME/note
    preconditions:
      - sh: command -v ruby
        msg: This command requires ruby.Please install ruby.
    cmds:
      - |
        DIR={{.CLI_ARGS}}
        [[ $DIR == */ ]] && DIR="${DIR%/}"

        # TEMPLATE_NUM=$((RANDOM % 3 + 1))
        TEMPLATE_NUM=$(ruby -e 'puts rand(1..3)')
        OUTPUT=$DIR/output.png
        ARTICLE=$DIR/$DIR.md

        note-cli create image -i ./icon.png --template $TEMPLATE_NUM -o $OUTPUT $ARTICLE
    silent: true
